menu:
  Home: / || fas fa-home
  Notes: /blog/ || fas fa-book-open
  Archives: /archives/ || fas fa-archive
  Categories: /categories/ || fas fa-folder-open
  Tags: /tags/ || fas fa-tags
  About: /about/ || fas fa-user

favicon: /img/favicon.jpg

avatar:
  img: /img/avatar.jpg
  effect: false

disable_top_img: true
index_img: false
default_top_img: false
index_top_img_height: 0

social:
  fab fa-github: https://github.com/tan1-Z || GitHub || "#24292e"
  fas fa-envelope: mailto:peit879@gmail.com || Email || "#4a4a4a"

aside:
  enable: true
  hide: true
  button: true
  mobile: false
  position: right

  card_author:
    enable: true
    description: Research notes, selected projects, and academic updates.
    button:
      enable: true
      icon: fab fa-github
      text: My GitHub
      link: https://github.com/tan1-Z

  card_announcement:
    enable: false
    content:

  card_recent_post:
    enable: true
    limit: 5

  card_categories:
    enable: true

  card_tags:
    enable: true

math:
  use: katex
  per_page: false
  hide_scrollbar: false

katex:
  copy_tex: false
